[dependencies]
base = "0.12.1"
map = "9.0.1"
itertools = "0.1.2"
vector = "0.2.0"
rxmodb = "0.1.5"
stableheapbtreemap = "1.5.0"
devefi-icrc-ledger = "1.1.4"
swbstable = "1.1.1"
rechain = "1.0.0"
icrc45 = "0.1.0"